<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bebidas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bebida" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:element name="codigo" type="xs:string"/>
                                <xs:element name="nombre" type="xs:string"/>
                            </xs:choice>
                            <xs:element name="precio" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
