<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hardwareCatalog">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="brand" type="xs:string"/>
                            <xs:element name="model" type="xs:string"/>
                            <xs:element name="specifications" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
